---
training:
  img_width: 64
  img_height: 64
  epochs: 50
  test_size: 0.4

logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple:
      format: '%(levelname)s -- %(message)s'
    precise:
      format: '%(asctime)s -- %(levelname)s -- %(processName)s %(filename)s:%(lineno)s -- %(message)s'

  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple

    info_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: INFO
      formatter: precise
      filename: log/info.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8

    error_file_handler:
      class: logging.handlers.RotatingFileHandler
      level: ERROR
      formatter: precise
      filename: log/errors.log
      maxBytes: 10485760 # 10MB
      backupCount: 20
      encoding: utf8

  loggers:
    main:
      level: INFO
      handlers: [console]
      propagate: no

  root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]